### ISSUE TITLE
Running TypeScript in REPL

### ISSUE THREAD

**Issue by XiNiHa** [esbuild-kit/esno#20]
`ts-node` supports running TypeScript code in REPL.
However, running `esno` just launches vanilla Node REPL and doesn't accept any TS code.
Will it be possible to support this in `esno`?

**Comment by privatenumber** [comment]
Added in [tsx 3.2.0](https://github.com/esbuild-kit/tsx/releases/tag/v3.2.0)

Hope it works well!
