### ISSUE TITLE
latest update breaks aliased imports

### ISSUE THREAD

**Issue by Mkassabov** [esbuild-kit/esno#24]
Updating from esno `0.14.0` to esno `0.15.0` breaks imports aliased by tsconfig paths. Maybe this issue should be escalated to the `tsx` package itself if esno is now based on tsx

**Comment by antfu** [comment]
Can you share a minimal reproduction? Thanks.

**Comment by Mkassabov** [comment]
@antfu 
here you go, let me know if you have any questions
https://github.com/Mkassabov/esno-bug

**Comment by wmelton** [comment]
Can confirm this is version related. Backed esno version down from 0.16 to 0.14 and paths definitions work again as expected.

**Comment by privatenumber** [comment]
It's a regression from changing esno to be an alias of tsx.

We're almost ready to release path support. Please help test if you can:
https://github.com/esbuild-kit/tsx/issues/3#issuecomment-1150638109

**Comment by privatenumber** [comment]
Released:
- https://github.com/esbuild-kit/cjs-loader/releases/tag/v2.1.0
- https://github.com/esbuild-kit/esm-loader/releases/tag/v2.2.0
