### ISSUE TITLE
esno v0.16.1 throwing error: Package subpath './dist/cli.js' is not defined by "exports"

### ISSUE THREAD

**Issue by aladdin-add** [esbuild-kit/esno#29]
```sh
Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './dist/cli.js' is not defined by "exports" in /Users/weiran/repo/dian/dn/node_modules/tsx/package.json imported from /Users/weiran/repo/dian/dn/node_modules/esno/esno.js
```

looks tsx adding `pkg.exports`, blocking the usage `import('tsx/dist/cli.js')`

**Comment by aliuq** [comment]
Got error now
![image](https://user-images.githubusercontent.com/11707934/169015992-05ecd647-c252-47f1-809a-546bd16428e3.png)

**Comment by antfu** [comment]
Yeah, wait for https://github.com/esbuild-kit/tsx/pull/11

**Comment by aliuq** [comment]
> Yeah, wait for [esbuild-kit/tsx#11](https://github.com/esbuild-kit/tsx/pull/11)

It seems to be a path problem, I found `.bin/esno` export `NODE_PATH`, but not used in `esno/esno.js`, I try to update it, then it works

```diff
#!/usr/bin/env node
- import('./node_modules/tsx/dist/cli.js')
+ import(`${process.env.NODE_PATH}/tsx/dist/cli.js`)
```

```sh
if [ -z "$NODE_PATH" ]; then
  export NODE_PATH="/home/liuq/apps/build_opencv/node_modules/.pnpm/node_modules"
else
  export NODE_PATH="$NODE_PATH:/home/liuq/apps/build_opencv/node_modules/.pnpm/node_modules"
fi
```

**Comment by aliuq** [comment]
I deleted the comment that just had an error
