### ISSUE TITLE
esno vs ts-node

### ISSUE THREAD

**Issue by abcd-ca** [esbuild-kit/esno#34]
Hello, I’m excited to try esno. Just heard about it on a podcast. How does it compare with ts-node? Is it Production ready?

Thank you

**Comment by antfu** [comment]
esno uses esbuild and it's much faster (but does not do typecheck). yes, it's production-ready but I'd never recommend to run `.ts` directly in production server

**Comment by classmatewu** [comment]
> but I'd never recommend to run .ts directly in production server.

why? and how should I do best?

**Comment by privatenumber** [comment]
Here's a comparison of esno/tsx vs ts-node (and other TypeScript runtimes):

https://github.com/privatenumber/ts-runtime-comparison
