### ISSUE TITLE
sourcemaps are broken in debug mode since aliasing to tsx

### ISSUE THREAD

**Issue by Newbie012** [esbuild-kit/esno#35]
Since esno aliases to `tsx`, I'm unable to debug my source files.

Before (`"esno": "0.14.0"`):

![image](https://user-images.githubusercontent.com/10504365/170450398-6adede21-3090-4b74-8356-a444f552e6bf.png)

After (`"esno": "0.16.3"`):

![image](https://user-images.githubusercontent.com/10504365/170450683-deff1ecd-b92d-43a7-aeac-8a743ecfaa43.png)

**Comment by privatenumber** [comment]
Should be fixed in the latest version. Try re-installing it so that it has the latest core-utils subdependency.
